MARA-52 토스트메시지 전역 객체로 변경
DDD-Community/fridge-link-web pull request #11
Opened 2024-02-02 18:46 UTC by a-honey

## 요구사항

이슈번호: [Mara-52](https://alsehf0316.atlassian.net/browse/MARA-52)

## 작업내용
- 토스트 메시지 컴포넌트 전역 변경(src/template/Layout.tsx)
- 토스트 메시지 타입별 스토리 작성

## 테스트 결과 또는 방법
![image](https://github.com/DDD-Community/fridge-link-web/assets/75254185/7c900622-2042-4266-8138-52d05f67051a)

2024-02-03 05:44 UTC, choipureum commented on src/components/organisms/IngredientAddModal.tsx
`Toast`같은 경우는 따로 hook으로 빼서 다른 곳에도 사용할 수 있게 하는 방향이 좋을 것 같습니다..! 
toast 이벤트를 fire 해주는 함수나 `set`이나 `remove` 도 구분하고 중복 토스트를 고려한 유니크 id값도 추가되어야 할 것 같습니다.

2024-02-03 06:00 UTC, choipureum requested changes
토스트 고생하셧슴당! 
해당 리뷰만 반영 부탁드립니당😀

2024-02-03 06:01 UTC, choipureum commented on src/components/atoms/ToastMessage.tsx
> +  const closeToast: () => void = () => {
`toast`를 추적할 수 있는 해시값 추가부탁드림니당

2024-02-04 07:03 UTC, a-honey commented
> 토스트 고생하셧슴당! 해당 리뷰만 반영 부탁드립니당😀

hook 추가했습니다 🌸🌸
id로 시간초과 후 hook에서 삭제하도록 수정했습니당

2024-02-04 14:01 UTC, hyeseon-han approved these changes

2024-02-05 00:11 UTC, choipureum commented on src/hooks/useToast.ts
> +    }, 2000);
해당부분 같은로직으로 직관성있게 `hideToast`로 사용하면 좋을 것 같네요!🙇‍♂️

2024-02-05 00:14 UTC, choipureum commented on src/hooks/useToast.ts
> +  const showToast: (message: string, type: ToastType) => void = (
[IMO]
`useCallback`처리 해도 좋을 것 같네요

2024-02-05 00:15 UTC, choipureum approved these changes
LGTM! 바로 반영 감사합니다! 훨씬 사용성 높아졌네용 수고하셨습니다🙇‍♂️

2024-02-05 12:05 UTC, ahyeon-jung commented on src/hooks/useToast.ts
> +  const showToast: (message: string, type: ToastType) => void = (
메모이제이션하면 좋겠네용 추가했습니다

2024-02-05 12:05 UTC, merged